/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tools;

import java.util.ArrayList;
import java.util.Collection;

/**
 *
 * @author Jason
 */
public class ResolvePanel extends javax.swing.JPanel {

    private Collection<modele.Objet_d_Instance> instancesADessiner;
    private int scale=5;
    /**
     * Creates new form ResolvePanel
     */
    public ResolvePanel() {
        initComponents();
        this.instancesADessiner = new ArrayList<>();
    }
    
    /************************* GETTERS ET SETTERS
     * @return  Collection
     ***********************/
    public Collection getInstancesADessiner() {
        return instancesADessiner;
    }

    public void setInstancesADessiner(Collection instancesADessiner) {
        this.instancesADessiner = instancesADessiner;
    }
    
    
    /****************************** METHODES ****************************/

    /**
     * Fonction qui permet d'augmenter le zoom sur le panel
     * Si l'echelle a atteint 2, on ne peux pas plus zoomer
     */
    public void zoomPlus(){
        if (this.scale <= 2)return;
        this.scale--;
    }
    
    /**
     * Fonction qui permet de diminuer le zoom sur le panel
     * Si l'echelle a atteint 9, on quitte
     */
    public void zoomMoins(){
        if (this.scale >=9)return;
        this.scale++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
