/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Toolkit;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.Collection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.BevelBorder;
import metier.DBRequests;
import modele.Instance;
import modele.Objet_d_Instance;
import test.TestEnti;

/**
 *
 * @author Jason
 */
public class Accueil extends javax.swing.JFrame {
    private Graphics g;
    private DBRequests dbr;
    public static int tailleDuPanel;
    
    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
        initialisationFenetre();   
        this.setG(this.myPanel1.getGraphics());        
        getAllInstance();
    }
    
    /**
     * Fonction qui permet de d'initialiser le modèle de la fenètre
     */
    private void initialisationFenetre(){
        this.setVisible(true);
        this.setTitle("OptiBox Accueil");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(dim.width, dim.height-50);

        // on place le Scroll
        this.jScrollPane2.setLocation(this.jList_instance.getWidth()+20, 5);
        // on lui met des dimensions
        Dimension dimScroll = new Dimension(dim.width-40-this.jList_instance.getWidth(),dim.height-150);
        this.jScrollPane2.setSize(dimScroll);
        
        
       Dimension dimPanel = new Dimension(dim.width-120-this.jList_instance.getWidth(),2500);
        this.myPanel1.setPreferredSize(dimPanel);
        this.setLocation(0, 0);
    }
        
    private void getAllInstance(){
        DefaultListModel dlm = new DefaultListModel();
        this.jList_instance.setModel(dlm);

        try {
            dbr = DBRequests.getInstance();
            dbr.getAllInstances();
            List<Instance> instances= dbr.getToutesLesInstances();
            for (Instance i : instances){
                dlm.addElement(i);
            }
        } catch (Exception ex) {
            //Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Impossible de charger l'ensemble des instances.\nVeuillez vérifier votre connection à la base de donnée.", "Erreur de chargement", HEIGHT);
            this.dispose();
        }              
    }
    
    public void afficherInstance(Instance i){
        Collection<Objet_d_Instance> ObjectsDeLInstance = i.getObjetsDeLInstance();
        this.myPanel1.setInstancesADessiner(ObjectsDeLInstance);
        this.myPanel1.repaint();
        System.out.println(this.myPanel1.getHeight());
    }

    public Graphics getG() {
        return g;
    }

    public void setG(Graphics g) {
        this.g = g;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_instance = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        myPanel1 = new tools.MyPanel();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.red);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(null);

        jScrollPane1.setBackground(java.awt.Color.red);

        jList_instance.setBackground(java.awt.Color.lightGray);
        jList_instance.setFont(new java.awt.Font("Montserrat Medium", 0, 36)); // NOI18N
        jList_instance.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_instance.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList_instance.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jList_instance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_instanceMouseClicked(evt);
            }
        });
        jList_instance.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_instanceValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList_instance);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 280, 580);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 200));
        jScrollPane2.setViewportView(myPanel1);

        myPanel1.setMaximumSize(new java.awt.Dimension(1500, 1500));
        myPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        myPanel1.setLayout(null);
        jScrollPane2.setViewportView(myPanel1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(380, 40, 620, 270);

        menuBar.setBackground(java.awt.Color.red);

        jMenu1.setText("File");
        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged

    }//GEN-LAST:event_formWindowStateChanged

    private void jList_instanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_instanceMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jList_instanceMouseClicked

    private void jList_instanceValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_instanceValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {//This line prevents double events
            int index = this.jList_instance.getSelectedIndex(); // on récupère l'index qui a été choisi dans la liste
            Object c = this.jList_instance.getModel().getElementAt(index); // on récupère l'objet
            afficherInstance((Instance)c); // on caste l'objet et on l'affiche
        }
    }//GEN-LAST:event_jList_instanceValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JList<String> jList_instance;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar menuBar;
    private tools.MyPanel myPanel1;
    // End of variables declaration//GEN-END:variables
}
