/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import metier.DBRequests;
import modele.Instance;


/**
 *
 * @author Jason
 */
public class Resolve extends javax.swing.JFrame {
    private DBRequests dbr;
    Dimension dimEcran;

    /**
     * Creates new form Resolve
     */
    public Resolve() {
        Accueil.getInstance().setVisible(false); // on cache la fenêtre OptiBox
        initComponents();
        initialisationFenetre();
        initialisationPanel();
    }
    
    /**
     * Creates new form Resolve
     */
    public Resolve(Instance i) {
        this();
        this.nom_instance_label.setText("Instance : "+i.getNom());
        this.nom_instance_label.setLocation(dimEcran.width/2, 15);
    }
    
    
    
     /**
     * Fonction qui permet de d'initialiser le modèle de la fenètre
     */
    private void initialisationFenetre(){
        this.setVisible(true);
        this.setTitle("OptiBox Résolution");
        dimEcran = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(dimEcran.width+5, dimEcran.height-50);
        this.setLocation(0,0);
    }
    
    /**
     * Fonction qui permet d'initialiser et de placer le panel sur la page
     */
    private void initialisationPanel(){
        // on ajuste la taille du panel
        Dimension dimPanel = new Dimension(this.getWidth()-40,100); // on enlève 40 pour pouvoir centrer plus bas
        this.resolvePanel1.setPreferredSize(dimPanel);
        this.resolvePanel1.setLocation(20, 30); // on le place au centre de la page, donc 20 de chaque côté à une hauteur de 30
        this.resolvePanel1.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zoom_label = new javax.swing.JLabel();
        zoom_plus = new javax.swing.JLabel();
        zoom_moins = new javax.swing.JLabel();
        nom_instance_label = new javax.swing.JLabel();
        resolvePanel1 = new tools.ResolvePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        zoom_label.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 24)); // NOI18N
        zoom_label.setForeground(new java.awt.Color(255, 51, 51));
        zoom_label.setText("Zoom");
        getContentPane().add(zoom_label);
        zoom_label.setBounds(40, 10, 76, 30);

        zoom_plus.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 36)); // NOI18N
        zoom_plus.setForeground(new java.awt.Color(255, 51, 51));
        zoom_plus.setText("+");
        zoom_plus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(zoom_plus);
        zoom_plus.setBounds(10, 39, 22, 23);

        zoom_moins.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 36)); // NOI18N
        zoom_moins.setForeground(new java.awt.Color(255, 51, 51));
        zoom_moins.setText("-");
        zoom_moins.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(zoom_moins);
        zoom_moins.setBounds(125, 40, 14, 21);

        nom_instance_label.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 24)); // NOI18N
        nom_instance_label.setText("jLabel1");
        getContentPane().add(nom_instance_label);
        nom_instance_label.setBounds(427, 10, 210, 30);

        javax.swing.GroupLayout resolvePanel1Layout = new javax.swing.GroupLayout(resolvePanel1);
        resolvePanel1.setLayout(resolvePanel1Layout);
        resolvePanel1Layout.setHorizontalGroup(
            resolvePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        resolvePanel1Layout.setVerticalGroup(
            resolvePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(resolvePanel1);
        resolvePanel1.setBounds(10, 80, 920, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        // ré afficher la page Accueil quand la page resolve se ferme
        Accueil.getInstance().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resolve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resolve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resolve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resolve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resolve();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nom_instance_label;
    private tools.ResolvePanel resolvePanel1;
    private javax.swing.JLabel zoom_label;
    private javax.swing.JLabel zoom_moins;
    private javax.swing.JLabel zoom_plus;
    // End of variables declaration//GEN-END:variables
}
